export default Object.seal({
  profileTitle: 'User Profile',
  profileDescription: 'Personal details, payments, and preferences.',
  paymentNotice: 'Add your CBU or alias to receive payments for your events.',
  profileLoadError: 'We could not load your details. You can try saving your profile again.',
  accountData: 'Account details',
  financialData: 'Financial details',
  alternativeEmail: 'Alternate email',
  saveChangesBtn: 'Save changes',
  savingBtn: 'Saving...',
  personalData: 'Personal Data',
  editImg: 'Edit Image',
  cbu: 'CBU',
  alias: 'Alias',
  name: 'Name',
  lastName: 'Last Name',
  specialDietTitle: 'Special Diet',
  veganDiet: 'Are you Vegan?',
  veganDietDescription: 'No animal-derived products',
  vegetarianDiet: 'Are you Vegetarian?',
  vegetarianDietDescription: 'No meat or fish',
  hypertensiveDiet: 'Are you Hypertensive?',
  hypertensiveDietDescription: 'Low sodium',
  celiacDiet: 'Are you Celiac?',
  celiacDietDescription: 'Gluten-free',
  saveBtn: 'SAVE',
  headerWelcome: 'Welcome: ',
  logoutBtn: 'LOGOUT',
  loginBtn: 'LOGIN',
  successMsg: 'Information successfully changed',
  failureMsg: "You couldn't update your information successfully",
  errorTypeFile: 'Profile image must be of type .png, .jpeg or .jpg',
  notificationsTitle: 'Notifications',
  activateNotifications: 'Activate Notifications',
  personalEmail: 'Personal Email',
  newEventNotification: 'A new event has been created',
  eventComingNotification: 'An event is about to start',
  penalizationStartedNotification: 'Your penalization has started',
  oneWeekDebtorNotification: 'You have been a debtor for a week',
  notificationDescription: 'I want to receive notifications when:',
  languageTitle: 'Language',
  languageLabel: 'Application language',
  spanishLanguage: 'Spanish (Argentina)',
  englishLanguage: 'English (United States)',
  themeTitle: 'Appearance',
  themeLabel: 'Application theme',
  lightTheme: 'Light',
  darkTheme: 'Dark',
  invalidEmail: 'The entered email is not valid',
  errorEmailRequired: 'Personal email is required to receive notifications',
});
