export default Object.seal({
  profileTitle: 'Perfil de Usuario',
  profileDescription: 'Datos personales, pagos y preferencias.',
  paymentNotice: 'Completá tu CBU o alias para poder recibir pagos en tus eventos.',
  profileLoadError: 'No pudimos cargar tus datos. Podés volver a intentar guardar el perfil.',
  accountData: 'Datos de tu cuenta',
  financialData: 'Información financiera',
  alternativeEmail: 'Correo alternativo',
  saveChangesBtn: 'Guardar cambios',
  savingBtn: 'Guardando...',
  personalData: 'Datos Personales',
  editImg: 'Editar Imagen',
  cbu: 'CBU',
  alias: 'Alias',
  name: 'Nombre',
  lastName: 'Apellido',
  specialDietTitle: 'Dieta Especial',
  veganDiet: '¿Sos Vegano?',
  veganDietDescription: 'Sin productos de origen animal',
  vegetarianDiet: '¿Sos Vegetariano?',
  vegetarianDietDescription: 'Sin carne ni pescado',
  hypertensiveDiet: '¿Sos Hipertenso?',
  hypertensiveDietDescription: 'Baja en sodio',
  celiacDiet: '¿Sos Celíaco?',
  celiacDietDescription: 'Sin gluten',
  saveBtn: 'GUARDAR',
  headerWelcome: 'Bienvenido: ',
  logoutBtn: 'SALIR',
  loginBtn: 'INICIAR SESIÓN',
  successMsg: 'La información se ha modificado con éxito',
  failureMsg: 'Ha habido un problema con la actualización de tu información',
  errorTypeFile: 'La imagen de perfil debe ser de tipo .png, .jpeg o .jpg',
  notificationsTitle: 'Notificaciones',
  activateNotifications: 'Activar Notificaciones',
  personalEmail: 'Correo Electrónico Personal',
  newEventNotification: 'Un nuevo evento ha sido creado',
  eventComingNotification: 'Un evento está por comenzar',
  penalizationStartedNotification: 'Tu penalización ha comenzado',
  oneWeekDebtorNotification: 'Has sido deudor por una semana',
  notificationDescription: 'Deseo recibir notificaciones cuando:',
  languageTitle: 'Idioma',
  languageLabel: 'Idioma de la aplicación',
  spanishLanguage: 'Español (Argentina)',
  englishLanguage: 'Inglés (Estados Unidos)',
  themeTitle: 'Apariencia',
  themeLabel: 'Tema de la aplicación',
  lightTheme: 'Claro',
  darkTheme: 'Oscuro',
  invalidEmail: 'El correo electrónico ingresado no es válido',
  errorEmailRequired: 'El correo electrónico personal es obligatorio para recibir notificaciones',
});
